version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  ignored_updates:
    - match:
        dependency_name: "govuk-frontend"
        version_requirement: "3.x"
    - match:
        dependency_name: "digitalmarketplace-govuk-frontend"
        version_requirement: "3.x"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
