version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  ignore:
  - dependency-name: "govuk-frontend"
    versions: "3.x"
  - dependency-name: "digitalmarketplace-govuk-frontend"
    versions: "3.x"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
