language: python
python:
  - "3.6"
before_install:
  - nvm install 10.16.3
install:
  - make requirements-dev yarn-install
script:
  - PYTEST_ARGS='--cov=app --cov-report=term-missing' make test
after_success:
  - coveralls
notifications:
  email: false
